language: node_js
sudo: false
branches:
  only:
  - gh-pages
env:
  global:
  - URL="https://w3c.github.io/resource-timing/W3CTRMANIFEST"
  - DECISION="http://www.w3.org/2015/06/24-webperf-minutes.html#item01"
  - secure: "XkbpT9szjCr2QbjK7xTD0+suar56yToEvwXnWGVvnzoUHLxyW0QoyD3po35ypmBPLhQDoYHo2f+UvzepPxMXrlB2xaRHA9JXWqOYOSLPc/kIUru3ZUjV98o/+8Jcde4dlfeiRdVBpWwM15Onu8yIc8ekVuLOr9unAuvwtFkFZIY="
script:
- echo "ok"
after_success:
- test $TRAVIS_PULL_REQUEST = false && curl "https://labs.w3.org/echidna/api/request" --data "url=$URL" --data "decision=$DECISION" --data "token=$TOKEN"